version: "3.5"

services:
  #TODO rewrite docker images
  gateway:
    container_name: fit_users_gateway
    image: bref/fpm-dev-gateway
    ports:
      - 8000:80
    volumes:
      - .:/var/task:ro
      - ./var/cache:/var/task/cache
      - ./var/log:/var/task/log
    depends_on:
      - php
    environment:
      HANDLER: public/index.php
  php:
    container_name: php
    image: bref/php-73-fpm-dev
    volumes:
      - .:/var/task:ro
  cli:
    container_name: cli
    image: bref/php-73
    volumes:
      - .:/var/task:ro
    entrypoint: php